### ISSUE TITLE
[ASK]  Model not training

### ISSUE THREAD

**Issue by LeDuySon** [microsoft/recommenders#1225]
Im using model Sli_rec for my custom dataset. I formatt my data as this notebook https://github.com/microsoft/recommenders/blob/master/examples/00_quick_start/sequential_recsys_amazondataset.ipynb suggest and then i run_eval on this model, every thing was fine but when training model its not output anything or raise any error. Can someone help me.
Im training on google colab about two hours but nothing happen
My parameters config: 
![Screenshot from 2020-10-29 16-54-51](https://user-images.githubusercontent.com/33374938/97553035-88f84f80-1a07-11eb-84b1-0ffe5193583e.png)

![Screenshot from 2020-10-29 16-49-24](https://user-images.githubusercontent.com/33374938/97552363-c01a3100-1a06-11eb-8433-37344d2a9408.png)

**Comment by miguelgfierro** [comment]
We haven't tested it in google colab, so not sure about the issue

**Comment by LeDuySon** [comment]
> We haven't tested it in google colab, so not sure about the issue

I have tested model on my computer too, but still nothing happen

**Comment by miguelgfierro** [comment]
can you please show what error do you get.

This notebook should pass, it is tested, can you please do:
```
pytest tests/integration/test_notebooks_gpu.py::test_slirec_quickstart_integration --disable-warnings

```

**Comment by LeDuySon** [comment]
> can you please show what error do you get.
> 
> This notebook should pass, it is tested, can you please do:
> 
> ```
> pytest tests/integration/test_notebooks_gpu.py::test_slirec_quickstart_integration --disable-warnings
> ```

I fixed it, thanks you. btw, how can i use this model to infer with 1 sample

**Comment by miguelgfierro** [comment]
`predict` can be used for that https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py#L215. You would need to input one example. If you want to do this in memory you have `infer`: https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/base_model.py#L379

**Comment by LeDuySon** [comment]
> `predict` can be used for that https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py#L215. You would need to input one example. If you want to do this in memory you have `infer`: https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/base_model.py#L379

output of model is built as a binary classification task, so when i have a user given a sequence of items that user has interacted, how can i predict top k for that user. Can you explain expicitly!!

**Comment by aidenpearce001** [comment]
> `predict` can be used for that https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/sequential/sequential_base_model.py#L215. You would need to input one example. If you want to do this in memory you have `infer`: https://github.com/microsoft/recommenders/blob/master/reco_utils/recommender/deeprec/models/base_model.py#L379

I still dont understand input format when inference, can u help me

**Comment by miguelgfierro** [comment]
> output of model is built as a binary classification task, so when i have a user given a sequence of items that user has interacted, how can i predict top k for that user. Can you explain expicitly!!

It is not easy to change from a rating problem to a ranking problem. What most people do is to order the probabilities and get the top k. I would recommend you to do that.

However, the most accurate way would be to change the loss function to a pairwise ranking loss like BPR. That would require you to change the loss, which is not straightforward.
