### ISSUE TITLE
[BUG]tests are failing. 

### ISSUE THREAD

**Issue by wutaomsft** [microsoft/recommenders#775]

**Comment by gramhagen** [comment]
several issues going on here
- master cpu is failing due to the nni smac issue @anargyri are you ok pushing the current staging solution to this to master? or are there changes we should make to the nni notebook?

- master gpu is failing due to metrics discrepancy with xdeepfm - could be something we can fix with setting seeds, @loomlike is this something you have time to look into?

- staging failures seem to be a temporary hiccup connecting to git. i queued them to rerun, so hopefully those will be fixed shortly

**Comment by anargyri** [comment]
I agree we should push staging until NNI fix the issue.

**Comment by miguelgfierro** [comment]
SAR issue is fixed. We still need to fix the issue with NNI https://github.com/microsoft/recommenders/issues/746

@loomlike I think you have a fix for the xdeepfm right? is this already in staging?

**Comment by gramhagen** [comment]
addressing the staging nni failure in #781

**Comment by loomlike** [comment]
Will take a look at xDeepFM one.

**Comment by loomlike** [comment]
Is xDeepFM test still failing? If so, please give me more context, i.e. would be nice to know specific test function names that fail. I don't see them from my machine or PRs.

**Comment by miguelgfierro** [comment]
I haven't seen it failing for a while, but not sure
